version: '2'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer-data:/data
    ports:
      - 9000:9000
    restart: unless-stopped
    networks:
      - app-network
  
  speedtest:
    image: openspeedtest/latest
    container_name: openspeedtest
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge