version: '2'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer-data:/data
    ports:
      - 9000:9000
    restart: unless-stopped
    networks:
      - app-network

volumes:
  ./docker.sock:
  ./portainer-data:

networks:
  app-network:
    driver: bridge