version: '3'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer-data:/data
    ports:
      - 9000:9000
    restart: unless-stopped
    networks:
      - app-network
  
  speedtest:
    image: openspeedtest/latest
    container_name: openspeedtest
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
    networks:
      - app-network

  dashbord:
    image: b4bz/homer
    container_name: homer
    ports:
      - 9055:8080
    restart: unless-stopped
    env_file: .var
    #ebter info from new user ($USER)
    environment:
      - USER=$USER
      - GROUP=$USER
      - UID=1001
      - GID=1001
    volumes:
      - ./homer:/www/assets
    networks:
      - app-network

networks:
  app-network:
    driver: bridge