version: '3'

dashbord:
    image: b4bz/homer
    container_name: homer
    ports:
      - 9055:8080
    restart: unless-stopped
    #ebter info from new user ($USER)
    environment:
      - USER=master
      - GROUP=master
      - UID=1001
      - GID=1001
    volumes:
      - ./homer:/www/assets
    networks:
      - app-network


version: '3'

services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    ports:
      - "8080:8080"
    volumes:
      - /etc/homer/assets/:/www/assets
    restart: unless-stopped
    networks:
      - app-network