version: '3'

services:
  nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager:v1.25.0
    ports:
      - "8181:8181"
      - "8080:8080"
      - "4443:4443"
    volumes:
      - "/home/master/docker/nginx-proxy-manager:/config:rw"