version: '3'

services:
  kodi:
    image: linuxserver/kodi-headless
    container_name: kodi
    ports:
      - "3010:8080"
      - "3011:9090"
      - "3012:9777"
    environment:
      - PUID=1001
      - PGID=1001
    volumes:
      - kodi-data:/config/.kodi
    restart: unless-stopped
    networks:
      - kodi-network

networks:
  kodi-network:
    external: true

volumes:
  kodi-data:
    driver: local