version: '3'

services:
  db:
    image: mysql:5.7.37
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - /home/master/docker/dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    depends_on:
      - db
    image: wordpress:5.8.3-php8.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    ports:
      - 7070:80
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=myuser
      - WORDPRESS_DB_PASSWORD=example
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - /home/master/docker/wordpress:/var/www/html