version: '3'

services:
  db:
    image: mysql:5.7.37
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=3_KDduEU#R2F
    volumes:
      - wpdb-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    depends_on:
      - db
    image: wordpress:5.8.3-php8.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    ports:
      - 41524:80
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=adminwb
      - WORDPRESS_DB_PASSWORD=X7Yd6*sx=FAw
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress-data:/var/www/html

volumes:
  wordpress-data:
    driver: local
  wpdb-data:
    driver: local